---
collections:

- name: ansible.posix
  version: 1.4.0

- name: community.general
  version: 4.8.5

- name: community.docker
  version: 2.7.0

roles:

- src: dev-sec.ssh-hardening
  version: "6.1.3"

- src: geerlingguy.ntp
  version: "2.3.0"

- src: nvidia.nvidia_driver
  version: "v2.3.0"

- src: nvidia.nvidia_docker
  version: "v1.2.4"

- src: nvidia.enroot
  version: "v0.5.0"

- src: geerlingguy.filebeat
  version: "3.4.0"

- src: https://github.com/DeepOps/ansible-role-chrony
  name: DeepOps.chrony
  version: 'c9022153036dfdde4e2b313aecde4a46cd6f6687'

- src: https://github.com/OSC/ood-ansible.git
  version: 'v2.0.6'

- src: gantsign.golang
  version: 2.4.0

- src: https://github.com/DeepOps/ansible-role-hosts.git
  version: 'c21a676088c07db3db3ac9332cf584eeb068e3fd'
  name: DeepOps.hosts