---
- name: Default installation
  hosts: default
  vars:
    ood_portal_generator: false
  roles:
    - role: ood-ansible

- name: Custom
  hosts: custom
  roles:
    - role: ood-ansible
  vars:
    ood_portal_generator: false
  vars_files:
    - vars/portal.yml