- hosts: all
  become: true
  tasks:
    - name: Only run cleanup if > 3600 seconds ago
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        autoremove: true
        autoclean: true
        purge: true
        install_recommends: false

    - name: Remove unnecessary software
      package:
        name: "{{ unnecessary_software }}"
        state: absent
        purge: true
        autoremove: true
        autoclean: true
      ignore_errors: true

    - name: Install necessary software
      package:
        name: "{{ necessary_software }}"
        state: present
        autoremove: true
        autoclean: true
        install_recommends: false

    - name: Stop and disable unnecessary services
      service:
        name: "{{ item }}"
        state: stopped
        enabled: no
      with_items: "{{ unnecessary_services }}"
      ignore_errors: true
