---
- hosts: all
  become: true
  tasks:
    - name: Prune everything (including non-dangling images)
      command: docker system prune -f -a
      ignore_errors: true
      register: docker_info

    - name: Print docker prune info
      ansible.builtin.debug:
        var: docker_info
