---
- hosts: all
  become: true

  tasks:
    - name: Set backward compatible values for ssh-hardening if not defined
      block:
        - set_fact:
            ssh_client_hardening: false
          when: ssh_client_hardening is undefined
        - set_fact:
            ssh_server_password_login: true
          when: ssh_server_password_login is undefined
        - set_fact:
            ssh_use_pam: true
          when: ssh_use_pam is undefined
        - set_fact:
            ssh_max_auth_retries: 10
          when: ssh_use_pam is undefined

    - name: Perform full patching
      package:
        name: "*"
        state: latest

    - name: Add "{{ admin_user }}" group
      group:
        name: "{{ admin_user }}"
        state: present

    - name: Add local user
      user:
        name: "{{ admin_user }}"
        group: "{{ admin_user }}"
        shell: /bin/bash
        home: /home/"{{ admin_user }}"
        create_home: yes
        state: present
      ignore_errors: true

    - name: Add SSH public key for user
      authorized_key:
        user: "{{ admin_user }}"
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        state: present

    - name: Add sudoer rule for local user
      template:
        dest: /etc/sudoers.d/{{ admin_user }}
        src: templates/admin_user.j2
        owner: root
        group: root
        mode: 0440
        validate: /usr/sbin/visudo -csf %s

    - name: Add hardened SSH config
      template:
        dest: /etc/ssh/sshd_config
        src: ./templates/sshd_config.j2
        owner: root
        group: root
        mode: 0600
      notify: Reload SSH

    - name: Add SSH port to internal zone
      firewalld:
        zone: internal
        service: ssh
        state: enabled
        immediate: yes
        permanent: yes

    - name: Add permitted networks to internal zone
      firewalld:
        zone: internal
        source: "{{ item }}"
        state: enabled
        immediate: yes
        permanent: yes
      with_items: "{{ allowed_ssh_networks }}"

    - name: Drop ssh from the public zone
      firewalld:
        zone: public
        service: ssh
        state: disabled
        immediate: yes
        permanent: yes

    - name: Set a message of the day
      template:
        dest: /etc/motd
        src: templates/motd.j2
        owner: root
        group: root
        mode: 0644

    - name: Set a login banner
      template:
        dest: "{{ item }}"
        src: templates/issue.j2
        owner: root
        group: root
        mode: 0644
      with_items:
        - /etc/issue
        - /etc/issue.net

    - name: Remove other motds
      file:
        path: "{{ item }}"
        state: absent
      with_items: "{{ unnecessary_motd }}"

  handlers:
    - name: Reload SSH
      service:
        name: sshd
        state: reloaded

- import_playbook: bootstrap/bootstrap-ssh.yml

- import_playbook: bootstrap/bootstrap-sudo.yml

- import_playbook: generic/chrony-client.yml

- import_playbook: generic/hosts.yml
