- hosts: all
  become: true
  roles:
    - name: devsec.hardening.os_hardening
    - name: devsec.hardening.ssh_hardening
  vars:
      sysctl_overwrite:
        # Enable IPv4 traffic forwarding.
        net.ipv4.ip_forward: 1
      sshd_custom_options:
        - ssh_allow_tcp_forwarding: 'yes'
