---
- hosts: all
  become: true
  tasks:
    - name: Update and upgrade installed packages
      apt:
        name: "*"
        state: latest
        update_cache: true
        autoremove: true
        autoclean: true
        install_recommends: false
        cache_valid_time: 3600

    - name: Register nvidia-smi output
      command: nvidia-smi --query-gpu=gpu_name,gpu_bus_id,driver_version --format=csv
      when: ansible_hostname in groups["gpu"]
      register: gpu_info
      ignore_errors: true

    - name: Print nvidia-smi info
      ansible.builtin.debug:
        var: gpu_info.stdout_lines
      when: ansible_hostname in groups["gpu"]

    - name: Is the docker daemon running?
      ansible.builtin.systemd:
        state: started
        name: docker
        enabled: true
        daemon_reload: true

    - name: Prune all docker images
      command: docker system prune -f -a
      ignore_errors: true
      register: docker_image_prune

    - name: Print docker image prune info
      ansible.builtin.debug:
        var: docker_image_prune.stdout_lines

    - name: Prune all docker networks
      command: docker network prune -f
      ignore_errors: true
      register: docker_network_prune

    - name: Print docker network prune info
      ansible.builtin.debug:
        var: docker_network_prune.stdout_lines