---
- hosts: gpu
  become: true
  tasks:
    - name: Purge if requested
      block:
        - name: do purge
          apt:
            name: "{{ item }}"
            state: absent
            purge: true
            autoremove: true
          loop:
            - nvidia-*
            - cuda
            - libnvidia-*
            - xserver-xorg-*
      when: purge == true

    - name: Install NVIDIA stuff
      block:

        - name: add nvidia-container-runtime gpg key
          apt_key:
            url: https://nvidia.github.io/nvidia-container-runtime/gpgkey
            state: present

        - name: ncr add apt source
          lineinfile:
            path: /etc/apt/sources.list.d/nvidia-container-runtime.list
            line: "{{ item }}"
            state: present
            create: true
          loop:
            - "deb https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/$(ARCH) /"
            - "deb https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu18.04/$(ARCH) /"

        - name: update docker runtime entry
          blockinfile:
            path: /etc/systemd/system/docker.service.d/override.conf
            block: |
              [Service]
              ExecStart=
              ExecStart=/usr/bin/dockerd --host=fd:// --add-runtime=nvidia=/usr/bin/nvidia-container-runtime
            state: present
            create: true

        - name: install libs
          apt:
            name: "{{ item }}"
            state: latest
            update_cache: true
          loop:
            - nvidia-driver-525-server
            - nvidia-container-runtime
          register: debian_cuda_installed

        - name: update CMAKE_CUDA_COMPILER variable
          lineinfile:
            path: /etc/environment
            line: 'CMAKE_CUDA_COMPILER="/usr/local/cuda-12.0/bin/nvcc"'
          register: compiler_env

        - name: restart docker
          systemd:
            state: restarted
            name: docker
            daemon_reload: true

        - name: reboot if needed
          reboot:
          when: purge == true
