---
- hosts: gpu
  become: true
  tasks:
    - name: Install NVIDIA Container Runtime
      block:
        - name: add nvidia-container-runtime gpg key
          apt_key:
            url: https://nvidia.github.io/nvidia-container-runtime/gpgkey
            state: present

        - name: ncr add apt source
          lineinfile:
            path: /etc/apt/sources.list.d/nvidia-container-runtime.list
            line: "{{ item }}"
            state: present
            create: true
          loop:
            - "deb https://nvidia.github.io/libnvidia-container/stable/ubuntu20.04/$(ARCH) /"
            - "deb https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu20.04/$(ARCH) /"

        - name: update docker runtime entry
          blockinfile:
            path: /etc/systemd/system/docker.service.d/override.conf
            block: |
              [Service]
              ExecStart=
              ExecStart=/usr/bin/dockerd --host=fd:// --add-runtime=nvidia=/usr/bin/nvidia-container-runtime
            state: present
            create: true

        - name: install libs
          apt:
            name: "{{ item }}"
            state: present
            update_cache: true
          loop:
            - nvidia-container-runtime
          register: debian_cuda_installed

        - name: Stop Docker
          systemd:
            state: stopped
            name: docker

        - name: Start Docker
          systemd:
            state: started
            name: docker
            enabled: true
            daemon_reload: true
