---
- hosts: gpu
  become: true

  tasks:
    - name: Remove Outdated Signing Key
      apt_key:
        id: 7fa2af80
        state: absent

    - name: Install the new cuda-keyring package
      block:
        - name: download cuda-keyring package
          get_url:
            url: https://developer.download.nvidia.com/compute/cuda/repos/{{ distro }}/{{ arch }}/cuda-keyring_1.0-1_all.deb
            dest: /tmp/cuda-keyring_1.0-1_all.deb

        - name: install cuda-keyring package
          apt:
            deb: /tmp/cuda-keyring_1.0-1_all.deb

        - name: run apt update
          apt:
            update_cache: true
    
    - name: Install cuda
      apt:
        name: cuda
        state: present
        install_recommends: false
        autoremove: true
      register: cuda_installed

    - name: Check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot if needed
      reboot:
      when: cuda_installed.changed or reboot_required_file.stat.exists == true
